name: Build and Push Docker image to GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        id: meta
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}:latest"
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker build -t ${{ steps.meta.outputs.image }} .
          docker push ${{ steps.meta.outputs.image }}
